---
title: ''
date: '2017-11-15 10:36 -0500'
text field: dereklieu
button stuff: false
published: false
select stuff: foo
lang:
  - en
  - fr
---
baseurl: /starter
permalink: pretty
markdown: rdiscount
prose:
  rooturl: ''
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "source"
        field:
          element: "hidden"
      - name: "title"
        field:
          element: "text"
      - name: 'image'
        field:
          element: "image"
          placeholder: "placeholder text"
          value: "default value"
          label: "this is an image"
          help: "need help? try this"
      - name: "date"
        field:
          element: "text"
          value: CURRENT_DATETIME
      - name: "textarea stuff1"
        field:
          element: "textarea"
          placeholder: "default"
      - name: "textarea stuff2"
        field:
          element: "textarea"
          placeholder: "default"
      - name: "textarea stuff3"
        field:
          element: "textarea"
          placeholder: "default"
      - name: "textarea stuff4"
        field:
          element: "textarea"
          placeholder: "default"
      - name: "text field"
        field:
          element: "text"
          label: "this some text field"
          value: CURRENT_USER
      - name: "button stuff"
        field:
          element: "button"
          on: "on"
          off: "off"
    _data:
      - name: "select stuff"
        field:
          element: "select"
          label: "single select"
          value: "foo"
          options:
            - name: ""
            - "foo"
            - name: "bar"
              value: "bar"
