baseurl: /starter
permalink: pretty
markdown: rdiscount
prose:
  rooturl: ''
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "source"
        field:
          element: "hidden"
      - name: "title"
        field:
          element: "text"
      - name: "date"
        field:
          element: "text"
          value: CURRENT_DATETIME
      - name: "textarea stuff1"
        field:
          element: "textarea"
          placeholder: "default"
      - name: "textarea stuff2"
        field:
          element: "textarea"
          placeholder: "default"
      - name: "textarea stuff3"
        field:
          element: "textarea"
          placeholder: "default"
      - name: "textarea stuff4"
        field:
          element: "textarea"
          placeholder: "default"
      - name: "text field"
        field:
          element: "text"
          label: "this some text field"
      - name: "button stuff"
        field:
          element: "button"
          on: "on"
          off: "off"
      - name: "select stuff"
        field:
          placeholder: "select this!"
          element: "select"
          value: "foo"
          options:
            - name: ""
            - value: "foo"
            - name: "bar"
              value: "bar"
      - name: "lang"
        field:
          element: "multiselect"
          label: "Select language"
          placeholder: "language"
          options:
            - name: "English"
              value: "en"
            - name: "French"
              value: "fr"
    _data:
      - name: "title"
        field:
          element: "text"
