# Site settings
title: ACLS Training Center
url: https://www.acls.net
permalink: pretty

# Post permalink
defaults:
  -
    scope:
      type: "pages"
    values:
      permalink: /:path/:basename:output_ext
      layout: page
  -
    scope:
      type: "posts"
    values:
      layout: post
  -
    scope:
      type: "articles"
    values:
      layout: page-without-sidebar
      parent-name: "Educational Articles"
      parent-href: "sitemap.htm"
  -
    scope:
      type: "states"
    values:
      layout: state

# Collections of files
collections:
  states:
    output: true
    permalink: "/:path.htm"
  algorithms:
    output: true
    permalink: "/:path.htm"
    layout: page-without-sidebar
  articles:
    output: true
    permalink: "/:path.htm"
    layout: page-without-sidebar
  medical-news:
    output: false

exclude:
  - README.md

prose:
  rooturl: ''
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "date"
        field:
          element: "text"
          label: "Date of news"
          help: "YYYY-MM-DD format"
      - name: "state"
        field:
          label: "Location of news (state)"
          element: "select"
          options:
            - name: "Alabama"
              value: "AL"
            - name: "Alaska"
              value: "AK"
            - name: "Arizona"
              value: "AZ"
            - name: "Arkansas"
              value: "AR"
            - name: "California"
              value: "CA"
            - name: "Colorado"
              value: "CO"
            - name: "Connecticut"
              value: "CT"
            - name: "Delaware"
              value: "DE"
            - name: "Florida"
              value: "FL"
            - name: "Georgia"
              value: "GA"
            - name: "Hawaii"
              value: "HI"
            - name: "Idaho"
              value: "ID"
            - name: "Illinois"
              value: "IL"
            - name: "Indiana"
              value: "IN"
            - name: "Iowa"
              value: "IA"
            - name: "Kansas"
              value: "KS"
            - name: "Kentucky"
              value: "KY"
            - name: "Louisiana"
              value: "LA"
            - name: "Maine"
              value: "ME"
            - name: "Maryland"
              value: "MD"
            - name: "Massachusetts"
              value: "MA"
            - name: "Michigan"
              value: "MI"
            - name: "Minnesota"
              value: "MN"
            - name: "Mississippi"
              value: "MS"
            - name: "Missouri"
              value: "MO"
            - name: "Montana"
              value: "MT"
            - name: "Nebraska"
              value: "NE"
            - name: "Nevada"
              value: "NV"
            - name: "New Hampshire"
              value: "NH"
            - name: "New Jersey"
              value: "NJ"
            - name: "New Mexico"
              value: "NM"
            - name: "New York"
              value: "NY"
            - name: "North Carolina"
              value: "NC"
            - name: "North Dakota"
              value: "ND"
            - name: "Ohio"
              value: "OH"
            - name: "Oklahoma"
              value: "OK"
            - name: "Oregon"
              value: "OR"
            - name: "Pennsylvania"
              value: "PA"
            - name: "Rhode Island"
              value: "RI"
            - name: "South Carolina"
              value: "SC"
            - name: "South Dakota"
              value: "SD"
            - name: "Tennessee"
              value: "TN"
            - name: "Texas"
              value: "TX"
            - name: "Utah"
              value: "UT"
            - name: "Vermont"
              value: "VT"
            - name: "Virginia"
              value: "VA"
            - name: "Washington"
              value: "WA"
            - name: "West Virginia"
              value: "WV"
            - name: "Wisconsin"
              value: "WI"
            - name: "Wyoming"
              value: "WY"
            - name: "Washington DC"
              value: "DC"
            - name: "Ontario"
              value: "ON"
            - name: "Quebec"
              value: "QC"
            - name: "Nova Scotia"
              value: "NS"
            - name: "New Brunswick"
              value: "NB"
            - name: "Manitoba"
              value: "MB"
            - name: "British Columbia"
              value: "BC"
            - name: "Prince Edward Island"
              value: "PE"
            - name: "Saskatchewan"
              value: "SK"
            - name: "Alberta"
              value: "AB"
            - name: "Newfoundland and Labrador"
              value: "NL"
      - name: "city"
        field:
          label: "Location of news (city)"
          element: "text"
      - name: "headline"
        field:
          label: "Headline of news story"
          help: "About 10 words"
          element: "text"
      - name: "link"
        field:
          label: "Link to main story"
          help: "A complete URL"
          element: "text"
