baseurl: /starter
permalink: pretty
markdown: rdiscount
prose:
  siteurl: 'http://athletesinaction.org'
  relativeLinks: 'http://athletesinaction.org'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    src/content:
      - name: "title"
        field:
          label: "Title"
          element: "text"
          help: "70 Character Max for Google and Social Media"
      - name: "summary"
        field:
            label: "Summary"
            element: "text"
      - name: "slug"
        field: 
          label: "URL of Page"
          element: "text"
          help: "should be the title, with dashed insterted instead of spaces"
      - name: "date"
        field:
          label: "date"
          help: "YYYY-MM-DD"
          element: "text"
      - name: "type"
        field:
          label: "Post Type"
          element: "select"
          options:
            - name: "Under Review"
              value: "underreview"
            - name: "Playbook"
              value: "devotion"
            - name: "Quickhit"
              value: "quickhit"
            - name: "Workout"
              value: "workout"
            - name: "InnerView"
              value: "innerview"
      - name: "author"
        field: 
          label: "Author"
          element: "text"
          help: "i.e.  First Last"
      - name: "keywords"
        field: 
          label: "Keywords"
          element: "text"
          help: "tags,seperarted,by, commas"
      - name: "color"
        field: 
          label: "Primary Color"
          element: "text"
          help: "don't add a #'"
      - name: "image"
        field: 
          label: "Image File Name"
          element: "text"
          help: "do not include path"
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          help: "Leaving unchecked will hide the file from the index and archive pages."
          value: true
    src/content/quickhits:
      - name: "title"
        field:
          label: "Title"
          element: "text"
          help: "70 Character Max for Google and Social Media"
      - name: "summary"
        field:
            label: "Summary"
            element: "text"
      - name: "slug"
        field: 
          label: "URL of Page"
          element: "text"
          help: "should be the title, with dashed insterted instead of spaces"
      - name: "date"
        field:
          label: "date"
          help: "YYYY-MM-DD"
          element: "text"
      - name: "type"
        field:
          element: "hidden"
          value: "quickhit"          
      - name: "author"
        field: 
          label: "Author"
          element: "text"
          help: "i.e.  First Last"
      - name: "keywords"
        field: 
          label: "Keywords"
          element: "text"
          help: "tags,seperarted,by, commas"
      - name: "image"
        field: 
          label: "Image File Name"
          element: "text"
          help: "Do not include path to the image.  Square and Rectangle version of the image should have the same filename."
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          help: "Leaving unchecked will hide the file from the index and archive pages."
          value: true
